/* GENERATED by tools/pour.js from kevins-water.json. Do not edit by hand.
   Kevin's own writing, verbatim, dealt across three faces in the order it came.
   His store is not modified by the pour and is not read at runtime. */
window.WATER = {
  "poured": "2026-08-14",
  "source": "kevins-water.json",
  "stones": 19,
  "faces": [
    [
      "i'm still deep in trying to get the nesi game to self assemble into the thing i've imagined.",
      "It's the four face writing, and word processing daily entry point.",
      "The use can change, gather, delete merge, analyse, observe patterns and grouping and structure between sentences.",
      "Patterns, can fal out of sentences into the soil.",
      "the tetra can drain to the next tetra.",
      "the heloistat mechanic run to the lightshop.",
      "Leve one the daily jounral is the most load bearing surface of everything."
    ],
    [
      "I built a counsel of 4 agents...",
      "Blind typing inputs to the other three surfaces.",
      "with highlight overlaying.",
      "The write is separated face by face until a clear lens is held in 3 faces...",
      "This becomes level two The light workshop, the water workshop, and the materials workshop.",
      "The filters and water table and freqency and sifting goes to the water table."
    ],
    [
      "buckminster fuller, The first tetra and level is the tank.",
      "Sequential hold the entire keylog as an unmutable entry.",
      "the soil view shows every sentence scattered, and hed individually.",
      "When the 3 faces light up..",
      "Each holds it's own tetra of 3 faces, and tools, and capabilities and functions.",
      "The solids table has it's own input ."
    ]
  ]
};
