// field_data.js — build THE FIELD's items from the live ledgers.
// Zero dependencies. Run: node tools/field_data.js
// Writes nesi/game2d/field_items.js — a plain <script> the surface reads.
//
// It reads. It never writes to a ledger, never answers, never routes.
// Routing is the hand's.

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..', '..', '..');
const OUT = path.resolve(__dirname, '..', 'field_items.js');

function lines(f) {
  const p = path.join(ROOT, f);
  if (!fs.existsSync(p)) return [];
  return fs.readFileSync(p, 'utf8').split('\n').filter(Boolean)
    .map(l => { try { return JSON.parse(l); } catch (e) { return null; } })
    .filter(Boolean);
}

// --- open gates: an "open" whose gate text has never been closed -------------
const gateKey = s => (s || '').split('(')[0].trim().slice(0, 60);
const g = lines('OPEN_GATES.jsonl');
const closed = new Set(g.filter(x => x.event === 'close').map(x => gateKey(x.gate)));

const gates = g
  .filter(x => x.event === 'open' && !closed.has(gateKey(x.gate)))
  .map(x => ({
    id: 'g:' + gateKey(x.gate),
    kind: 'gate',
    ts: x.ts,
    title: gateKey(x.gate) || '(unnamed gate)',
    body: (x.gate || '').slice(0, 900)
  }));

// --- decisions: "offered" never answered and never superseded ---------------
const dKey = x => x.session + '|' + x.tile;
const d = lines('DECISIONS_OFFERED.jsonl');
const settled = new Set(
  d.filter(x => x.event === 'answered' || x.event === 'superseded').map(dKey)
);

const seen = new Set();
const decisions = d
  .filter(x => x.event === 'offered' && !settled.has(dKey(x)))
  .filter(x => {                                   // same question re-offered many times
    const s = (x.one_liner || '').slice(0, 50);
    if (!s || seen.has(s)) return false;
    seen.add(s);
    return true;
  })
  .map(x => ({
    id: 'd:' + dKey(x),
    kind: 'decision',
    ts: x.ts,
    title: (x.one_liner || '').split(/[—:]/)[0].trim().slice(0, 70),
    body: (x.one_liner || '') +
      (x.options ? '\n\n' + Object.values(x.options).map(o => '· ' + o).join('\n') : '')
  }));

const items = gates.concat(decisions).sort((a, b) => (a.ts < b.ts ? -1 : 1));

fs.writeFileSync(
  OUT,
  '// GENERATED by tools/field_data.js — do not hand-edit.\n' +
  '// ' + gates.length + ' gates standing · ' + decisions.length + ' decisions unanswered\n' +
  'window.FIELD_ITEMS = ' + JSON.stringify(items, null, 0) + ';\n'
);

console.log('gates standing      ', gates.length);
console.log('decisions unanswered', decisions.length);
console.log('written             ', path.relative(ROOT, OUT));
