// gather.js — carry Kevin's real water into the regathered world, and touch nothing.
//
// THE WATER SEAM, S4 (2026-08-13): every walk runs on a copy of his real poured
// water, his store untouched, never on synthetic stones. Read-only, always.
//
// It emits TWO shapes on purpose, because two instruments have opposite laws:
//
//   WATER.stones — {n, text} VERBATIM. For the drop and the sounding, where the
//                  law is that his words come back exactly as he wrote them.
//   WATER.pile   — {ref, extent, settled} SHAPE ONLY. For the tarp, whose law is
//                  "not one character of text." Size is how big a thing is,
//                  settled is how long it has lain there. Nothing else crosses.
//
// The tarp must never be handed WATER.stones. That is the whole instrument.
//
//   node tools/gather.js

const fs = require('fs');
const path = require('path');

const ROOT  = path.join(__dirname, '..');
const STORE = path.join(ROOT, 'kevins-water.json');
const OUT   = path.join(ROOT, 'world_water.js');

if (!fs.existsSync(STORE)) {
  console.error('no kevins-water.json — refusing to invent stones. Nothing written.');
  process.exit(1);
}

const S = JSON.parse(fs.readFileSync(STORE, 'utf8'));   // read-only. never written.
const tank = Array.isArray(S.tank) ? S.tank : [];

if (!tank.length) {
  console.error('his store holds no stones — refusing to fabricate a pile. Nothing written.');
  process.exit(1);
}

// verbatim, in the order the river brought them. nothing sorted, nothing scored.
const stones = tank.map(s => ({ n: s.n, text: String(s.text || '') }));

// shape only. extent from length, settled from position in the run — both
// normalised against the pile itself, never against a target.
const lens = stones.map(s => s.text.length);
const maxL = Math.max.apply(null, lens);
const pile = stones.map((s, i) => ({
  ref:     'r' + s.n,
  extent:  maxL ? +(s.text.length / maxL).toFixed(3) : 0,
  settled: stones.length > 1 ? +(1 - i / (stones.length - 1)).toFixed(3) : 1
}));

fs.writeFileSync(
  OUT,
  '// GENERATED by tools/gather.js from kevins-water.json — do not hand-edit.\n' +
  '// His store was opened read-only and is unchanged.\n' +
  'window.WATER = ' + JSON.stringify({ stones: stones, pile: pile }) + ';\n'
);

console.log('stones (verbatim) ', stones.length);
console.log('pile   (shape only)', pile.length, '— no text crosses');
console.log('written           ', path.relative(ROOT, OUT));
