#!/usr/bin/env node
/* pour.js — carry the keeper's real poured water into the level, and touch nothing.
 *
 * THE WATER SEAM, S4 (2026-08-13, the keeper's order):
 *   "every game walk runs on a copy of the keeper's real poured water — his store
 *    untouched — never on synthetic stones. A build that drops the writing fails
 *    its own walk. Copy in, never read-write his store."
 *
 * So this reads keepers-water.json and writes level_one_water.js. It opens the
 * store READ-ONLY and never writes to it, never reorders it, never rewrites a
 * character of it.
 *
 * THE SEPARATION IS THE KEEPER'S OWN, verbatim from his store (n:34):
 *   "The write is separated face by face until a clear lens is held in 3
 *    faces... When the 3 faces light up.. the tetra can drain to the next tetra."
 *
 * The sentences are dealt across the three faces IN THE ORDER THEY CAME. That is
 * the river's own order — the one arrangement the corpus already names and the
 * only one that computes nothing. Nothing here measures kinship, similarity, or
 * theme; a bad kinship measure would quietly become a claim about his thinking.
 *
 *   node tools/pour.js
 */
const fs = require("fs");
const path = require("path");

const ROOT  = path.join(__dirname, "..");
const STORE = path.join(ROOT, "keepers-water.json");
const OUT   = path.join(ROOT, "level_one_water.js");

if (!fs.existsSync(STORE)) {
  console.error("pour: no store at " + STORE + " — nothing poured, level left as it was.");
  process.exit(1);
}

// READ ONLY. This file is never opened for writing anywhere in this script.
const store = JSON.parse(fs.readFileSync(STORE, "utf8"));

// The stones are his sentences, as he laid them. Verbatim, in order.
const stones = (store.tank || [])
  .map(s => (s && typeof s.text === "string") ? s.text.trim() : "")
  .filter(Boolean);

if (stones.length < 3) {
  console.error("pour: only " + stones.length + " stone(s) in the tank — the tetra needs three faces.");
  process.exit(1);
}

// Deal face by face, as it came. Round-robin so all three faces carry the run of
// the writing rather than its beginning, middle and end.
const faces = [[], [], []];
stones.forEach((s, i) => faces[i % 3].push(s));

const payload = {
  poured: new Date().toISOString().slice(0, 10),
  source: "keepers-water.json",
  stones: stones.length,
  faces: faces
};

fs.writeFileSync(OUT,
  "/* GENERATED by tools/pour.js from keepers-water.json. Do not edit by hand.\n" +
  "   the keeper's own writing, verbatim, dealt across three faces in the order it came.\n" +
  "   His store is not modified by the pour and is not read at runtime. */\n" +
  "window.WATER = " + JSON.stringify(payload, null, 2) + ";\n",
  "utf8");

console.log("pour: " + stones.length + " stone(s) → three faces of " +
  faces.map(f => f.length).join(" / ") + "  →  " + path.basename(OUT));
console.log("pour: store untouched (" + fs.statSync(STORE).size + " bytes, read-only).");
